---
linters-settings:
  errcheck:
    check-blank: true
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  gosec:
    severity: medium
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
  disable:
    - typecheck
    - dupl
    - interfacer
    - maligned
    - lll
    - golint
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
