---
run:
  timeout: 5m
  go: '1.24'

linters-settings:
  errcheck:
    check-blank: true
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  gosec:
    severity: medium
  misspell:
    locale: US
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 88

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - gocyclo
    - lll
  disable:
    - typecheck
    - dupl
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
