---
extends: default

rules:
  line-length:
    max: 88
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  document-start: disable
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  trailing-spaces: disable
  braces: disable
  syntax: disable

exclude: |
  charts/*/templates/*
  .github/workflows/*.yml
