services:
  api:
    build: .
    container_name: dlv-backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/dlv
      - SECRET_KEY=change-me-in-prod
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j123
    ports:
      - "8000:8000"
    volumes:
      # Mount only required sources to avoid bringing ignored files into the container
      - ./app:/app/app
      - ./main.py:/app/main.py
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - neo4j

  postgres:
    image: postgres:15
    container_name: dlv-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dlv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    container_name: dlv-neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    depends_on:
      - postgres

volumes:
  pgdata:
  neo4jdata:
  neo4jlogs:
