# Example: Spark-only lineage tracking

collectors:
  spark:
    enabled: true
    historyServerUrl: "http://spark-history-server:18080"
    refreshInterval: 5s
  
  airflow:
    enabled: false
  
  kafka:
    enabled: false
  
  flink:
    enabled: false

processor:
  graphdb:
    provider: "neo4j"
    neo4j:
      url: "bolt://neo4j:7687"
      username: "neo4j"
      password: "changeme"
      database: "spark_lineage"
  
  autoDiscover:
    enabled: true
    sources:
      - spark
  
  maxDepth: 15
  
  updateInterval: 5s

frontend:
  enabled: true
  
  visualization:
    layout: "hierarchical"
    showLabels: true
  
  features:
    realtimeUpdates: true
    whatIfAnalysis: true
    impactAnalysis: true

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: spark-lineage.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

