apiVersion: v2
name: dlv
description: A Helm chart for Data Lineage Visualizer - Track and visualize data flow in real-time across your data pipeline
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/dnguyenngoc/dlv/main/icon.png
keywords:
  - data-lineage
  - real-time
  - visualization
  - spark
  - airflow
  - kafka
  - bigdata
  - kubernetes
  - helm
  - authentication
  - rbac
maintainers:
  - name: Data Lineage Visualizer Team
    email: dev@dlv.local
home: https://github.com/dnguyenngoc/dlv
sources:
  - https://github.com/dnguyenngoc/dlv
dependencies:
  - name: postgresql
    version: "~12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled

