# Default values for dlv
# This is a YAML-formatted file.

replicaCount: 1

image:
  # Docker image repository
  # Examples:
  #   docker.io/duynguyenngoc/dlv       # Docker Hub
  #   ghcr.io/dnguyenngoc/dlv          # GitHub Container Registry
  #   gcr.io/your-project/dlv          # Google Container Registry
  #   your-registry.internal/dlv       # Private registry
  repository: docker.io/duynguyenngoc/dlv
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Image pull secrets
imagePullSecrets: []

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Collector configuration
collectors:
  # Apache Spark integration
  spark:
    enabled: true
    historyServerUrl: "http://spark-history-server:18080"
    refreshInterval: 5s

  # Apache Airflow integration
  airflow:
    enabled: true
    apiUrl: "http://airflow-webserver:8080"
    username: "admin"
    password: ""
    refreshInterval: 10s

  # Apache Kafka integration
  kafka:
    enabled: true
    brokers: "kafka:9092"
    refreshInterval: 5s

  # Apache Flink integration
  flink:
    enabled: true
    restPort: 8081
    restHost: "flink-jobmanager"
    refreshInterval: 5s

# Lineage processor configuration
processor:
  # Graph database backend
  graphdb:
    provider: "neo4j"  # neo4j, arangodb, gremlin
    neo4j:
      url: "bolt://neo4j:7687"
      username: "neo4j"
      password: ""
      database: "lineage"
    arangodb:
      url: "http://arangodb:8529"
      username: "root"
      password: ""
      database: "lineage"

  # Auto-discovery settings
  autoDiscover:
    enabled: true
    sources:
      - spark
      - airflow
      - kafka
      - flink

  # Lineage tracking depth
  maxDepth: 10

  # Real-time update interval
  updateInterval: 5s

# Frontend configuration
frontend:
  enabled: true
  image:
    # Frontend Docker image repository
    # Examples:
    #   docker.io/duynguyenngoc/dlv-ui  # Docker Hub
    #   ghcr.io/dnguyenngoc/dlv-ui     # GitHub Container Registry
    repository: docker.io/duynguyenngoc/dlv-ui
    pullPolicy: IfNotPresent
    tag: "latest"

  # Graph visualization settings
  visualization:
    layout: "force-directed"  # force-directed, hierarchical, circular
    nodeSize: "auto"  # auto, fixed
    showLabels: true
    animationSpeed: 500

  # Features
  features:
    realtimeUpdates: true
    streamingMode: true
    whatIfAnalysis: true
    impactAnalysis: true
    timelineView: true

# Service configuration
service:
  type: ClusterIP
  port: 8080
  frontendPort: 3000

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: dlv.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Persistent storage
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Node selector, tolerations, affinity
nodeSelector: {}
tolerations: []
affinity: {}

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Environment variables
env: []
  # - name: CUSTOM_VAR
  #   value: "value"

# Probes
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics

# Logging
logging:
  level: info
  format: json

