name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Lint Helm Chart
        run: helm lint charts/dlv

      - name: Validate Chart Schema
        run: |
          helm dependency update charts/dlv
          helm package charts/dlv

      - name: Template Rendering Test
        run: |
          helm template dlv ./charts/dlv \
            --namespace lineage \
            --debug > /dev/null

      - name: Check YAML syntax
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml

